### ISSUE TITLE
Schematics could fill barrels (as option or per default)

### ISSUE THREAD

**Issue by StenCalDabran** [GregOnNet/kentan#3]
Often an index.ts barrel file is in the src/app/test/sketches folder.
It exports the sketches in the form 
`export * from './example.sketch';`
Sketches generated by schematic could gain an entry there right away.

**Comment by GregOnNet** [comment]
Wow, good catch.
I consider adding this feature.

I should be an opt-in since not everyone uses barrel files.

It could be a simple rule: _When ./index.ts exists and contains `export` statements add the path of the Sketch._

**Comment by GregOnNet** [comment]
I moved this request to the kentan-schematics repository: https://github.com/GregOnNet/kentan-schematics/issues/9
